name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["CI/CD Pipelineo it"]
    branches: [ main, master, azure-deployment ]
    types: [completed]

env:
  AZURE_WEBAPP_NAME: your-app-name    # Change this to your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
